inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.6

  Exclude:
    - 'db/schema.rb'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false