require:
  - rubocop-performance
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.6

  Exclude:
    - 'db/schema.rb'
    - 'bin/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Metrics/BlockLength:
  Max: 35

Style/Documentation:
  Enabled: false

RSpec/LetSetup:
  Enabled: false
