version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root

      - image: circleci/postgres:11
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: easy-lives_test
          POSTGRES_PASSWORD: secret

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies- # Fallback to using the latest cache if no exact match is found

      - run: yarn
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run: bundle exec rubocop
      - run: bundle exec rspec --format documentation

workflows:
  default:
    jobs:
      - build
